------------------------------------------------------------------------
-- HealthDB – Kimball Star Schema
-- Mortality & Life Expectancy measures from World Bank
-- Source: SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE
-- Grain: one row per country per year
------------------------------------------------------------------------

CREATE OR REPLACE DATABASE HEALTHDB;
CREATE SCHEMA HEALTHDB.DW;

------------------------------------------------------------------------
-- DIM_DATE (year grain)
------------------------------------------------------------------------
CREATE OR REPLACE TABLE HEALTHDB.DW.DIM_DATE (
    DATE_KEY       INT          NOT NULL PRIMARY KEY,
    FULL_DATE      DATE         NOT NULL,
    YEAR           INT          NOT NULL,
    DECADE         VARCHAR(10)  NOT NULL
)
AS
SELECT
    YEAR(DATE)                                      AS DATE_KEY,
    DATE                                            AS FULL_DATE,
    YEAR(DATE)                                      AS YEAR,
    (FLOOR(YEAR(DATE) / 10) * 10)::VARCHAR || 's'  AS DECADE
FROM (
    SELECT DISTINCT DATE
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.WORLD_BANK_TIMESERIES
    WHERE VARIABLE IN (
        'ESG_SP.DYN.LE00.IN','WDI_SP.DYN.LE00.FE.IN','WDI_SP.DYN.LE00.MA.IN',
        'WDI_SH.STA.MMRT','WDI_SH.STA.MMRT.NE',
        'ESG_SH.DYN.MORT','WDI_SH.DYN.MORT.FE','WDI_SH.DYN.MORT.MA',
        'WDI_SP.DYN.IMRT.IN','WDI_SP.DYN.IMRT.FE.IN','WDI_SP.DYN.IMRT.MA.IN',
        'WDI_SH.DYN.NMRT',
        'WDI_SP.DYN.AMRT.FE','WDI_SP.DYN.AMRT.MA',
        'WDI_SH.DYN.NCOM.ZS','WDI_SH.DYN.NCOM.FE.ZS','WDI_SH.DYN.NCOM.MA.ZS',
        'WDI_SH.STA.AIRP.P5','WDI_SH.STA.AIRP.FE.P5','WDI_SH.STA.AIRP.MA.P5',
        'WDI_SH.STA.WASH.P5','WDI_SH.STA.TRAF.P5',
        'WDI_SH.STA.POIS.P5','WDI_SH.STA.POIS.P5.FE','WDI_SH.STA.POIS.P5.MA',
        'WDI_SH.STA.SUIC.P5','WDI_SH.STA.SUIC.FE.P5','WDI_SH.STA.SUIC.MA.P5'
    )
);

------------------------------------------------------------------------
-- DIM_GEOGRAPHY
------------------------------------------------------------------------
CREATE OR REPLACE TABLE HEALTHDB.DW.DIM_GEOGRAPHY (
    GEO_KEY        VARCHAR(50)  NOT NULL PRIMARY KEY,
    GEO_NAME       VARCHAR(200),
    LEVEL          VARCHAR(50),
    ISO_NAME       VARCHAR(200),
    ISO_ALPHA2     VARCHAR(5),
    ISO_ALPHA3     VARCHAR(5),
    ISO_NUMERIC    VARCHAR(10)
)
AS
SELECT DISTINCT
    g.GEO_ID        AS GEO_KEY,
    g.GEO_NAME,
    g.LEVEL,
    g.ISO_NAME,
    g.ISO_ALPHA2,
    g.ISO_ALPHA3,
    g.ISO_NUMERIC_CODE AS ISO_NUMERIC
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g
WHERE g.GEO_ID IN (
    SELECT DISTINCT GEO_ID
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.WORLD_BANK_TIMESERIES
    WHERE VARIABLE IN (
        'ESG_SP.DYN.LE00.IN','WDI_SP.DYN.LE00.FE.IN','WDI_SP.DYN.LE00.MA.IN',
        'WDI_SH.STA.MMRT','WDI_SH.STA.MMRT.NE',
        'ESG_SH.DYN.MORT','WDI_SH.DYN.MORT.FE','WDI_SH.DYN.MORT.MA',
        'WDI_SP.DYN.IMRT.IN','WDI_SP.DYN.IMRT.FE.IN','WDI_SP.DYN.IMRT.MA.IN',
        'WDI_SH.DYN.NMRT',
        'WDI_SP.DYN.AMRT.FE','WDI_SP.DYN.AMRT.MA',
        'WDI_SH.DYN.NCOM.ZS','WDI_SH.DYN.NCOM.FE.ZS','WDI_SH.DYN.NCOM.MA.ZS',
        'WDI_SH.STA.AIRP.P5','WDI_SH.STA.AIRP.FE.P5','WDI_SH.STA.AIRP.MA.P5',
        'WDI_SH.STA.WASH.P5','WDI_SH.STA.TRAF.P5',
        'WDI_SH.STA.POIS.P5','WDI_SH.STA.POIS.P5.FE','WDI_SH.STA.POIS.P5.MA',
        'WDI_SH.STA.SUIC.P5','WDI_SH.STA.SUIC.FE.P5','WDI_SH.STA.SUIC.MA.P5'
    )
);

------------------------------------------------------------------------
-- FACT_HEALTH_MEASURES – pivoted: 28 measure columns
-- Grain: one row per geography + year
------------------------------------------------------------------------
CREATE OR REPLACE TABLE HEALTHDB.DW.FACT_HEALTH_MEASURES (
    DATE_KEY                              INT          NOT NULL,
    GEO_KEY                               VARCHAR(50)  NOT NULL,

    LIFE_EXPECTANCY_TOTAL                 FLOAT,
    LIFE_EXPECTANCY_FEMALE                FLOAT,
    LIFE_EXPECTANCY_MALE                  FLOAT,

    MATERNAL_MORTALITY_MODELED            FLOAT,
    MATERNAL_MORTALITY_NATIONAL           FLOAT,

    MORTALITY_UNDER5_TOTAL                FLOAT,
    MORTALITY_UNDER5_FEMALE               FLOAT,
    MORTALITY_UNDER5_MALE                 FLOAT,
    MORTALITY_INFANT_TOTAL                FLOAT,
    MORTALITY_INFANT_FEMALE               FLOAT,
    MORTALITY_INFANT_MALE                 FLOAT,
    MORTALITY_NEONATAL                    FLOAT,

    MORTALITY_ADULT_FEMALE                FLOAT,
    MORTALITY_ADULT_MALE                  FLOAT,

    MORTALITY_NCD_TOTAL                   FLOAT,
    MORTALITY_NCD_FEMALE                  FLOAT,
    MORTALITY_NCD_MALE                    FLOAT,

    MORTALITY_AIR_POLLUTION_TOTAL         FLOAT,
    MORTALITY_AIR_POLLUTION_FEMALE        FLOAT,
    MORTALITY_AIR_POLLUTION_MALE          FLOAT,

    MORTALITY_UNSAFE_WATER                FLOAT,
    MORTALITY_ROAD_TRAFFIC                FLOAT,
    MORTALITY_POISONING_TOTAL             FLOAT,
    MORTALITY_POISONING_FEMALE            FLOAT,
    MORTALITY_POISONING_MALE              FLOAT,

    MORTALITY_SUICIDE_TOTAL               FLOAT,
    MORTALITY_SUICIDE_FEMALE              FLOAT,
    MORTALITY_SUICIDE_MALE                FLOAT,

    PRIMARY KEY (DATE_KEY, GEO_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES HEALTHDB.DW.DIM_DATE(DATE_KEY),
    FOREIGN KEY (GEO_KEY)  REFERENCES HEALTHDB.DW.DIM_GEOGRAPHY(GEO_KEY)
)
AS
WITH src AS (
    SELECT
        YEAR(DATE) AS DATE_KEY,
        GEO_ID     AS GEO_KEY,
        VARIABLE,
        VALUE
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.WORLD_BANK_TIMESERIES
    WHERE VARIABLE IN (
        'ESG_SP.DYN.LE00.IN','WDI_SP.DYN.LE00.FE.IN','WDI_SP.DYN.LE00.MA.IN',
        'WDI_SH.STA.MMRT','WDI_SH.STA.MMRT.NE',
        'ESG_SH.DYN.MORT','WDI_SH.DYN.MORT.FE','WDI_SH.DYN.MORT.MA',
        'WDI_SP.DYN.IMRT.IN','WDI_SP.DYN.IMRT.FE.IN','WDI_SP.DYN.IMRT.MA.IN',
        'WDI_SH.DYN.NMRT',
        'WDI_SP.DYN.AMRT.FE','WDI_SP.DYN.AMRT.MA',
        'WDI_SH.DYN.NCOM.ZS','WDI_SH.DYN.NCOM.FE.ZS','WDI_SH.DYN.NCOM.MA.ZS',
        'WDI_SH.STA.AIRP.P5','WDI_SH.STA.AIRP.FE.P5','WDI_SH.STA.AIRP.MA.P5',
        'WDI_SH.STA.WASH.P5','WDI_SH.STA.TRAF.P5',
        'WDI_SH.STA.POIS.P5','WDI_SH.STA.POIS.P5.FE','WDI_SH.STA.POIS.P5.MA',
        'WDI_SH.STA.SUIC.P5','WDI_SH.STA.SUIC.FE.P5','WDI_SH.STA.SUIC.MA.P5'
    )
)
SELECT
    DATE_KEY,
    GEO_KEY,
    MAX(CASE WHEN VARIABLE = 'ESG_SP.DYN.LE00.IN'       THEN VALUE END) AS LIFE_EXPECTANCY_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.LE00.FE.IN'    THEN VALUE END) AS LIFE_EXPECTANCY_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.LE00.MA.IN'    THEN VALUE END) AS LIFE_EXPECTANCY_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.MMRT'          THEN VALUE END) AS MATERNAL_MORTALITY_MODELED,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.MMRT.NE'       THEN VALUE END) AS MATERNAL_MORTALITY_NATIONAL,
    MAX(CASE WHEN VARIABLE = 'ESG_SH.DYN.MORT'          THEN VALUE END) AS MORTALITY_UNDER5_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.MORT.FE'       THEN VALUE END) AS MORTALITY_UNDER5_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.MORT.MA'       THEN VALUE END) AS MORTALITY_UNDER5_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.IMRT.IN'       THEN VALUE END) AS MORTALITY_INFANT_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.IMRT.FE.IN'    THEN VALUE END) AS MORTALITY_INFANT_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.IMRT.MA.IN'    THEN VALUE END) AS MORTALITY_INFANT_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.NMRT'          THEN VALUE END) AS MORTALITY_NEONATAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.AMRT.FE'       THEN VALUE END) AS MORTALITY_ADULT_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SP.DYN.AMRT.MA'       THEN VALUE END) AS MORTALITY_ADULT_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.NCOM.ZS'       THEN VALUE END) AS MORTALITY_NCD_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.NCOM.FE.ZS'    THEN VALUE END) AS MORTALITY_NCD_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.DYN.NCOM.MA.ZS'    THEN VALUE END) AS MORTALITY_NCD_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.AIRP.P5'       THEN VALUE END) AS MORTALITY_AIR_POLLUTION_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.AIRP.FE.P5'    THEN VALUE END) AS MORTALITY_AIR_POLLUTION_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.AIRP.MA.P5'    THEN VALUE END) AS MORTALITY_AIR_POLLUTION_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.WASH.P5'       THEN VALUE END) AS MORTALITY_UNSAFE_WATER,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.TRAF.P5'       THEN VALUE END) AS MORTALITY_ROAD_TRAFFIC,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.POIS.P5'       THEN VALUE END) AS MORTALITY_POISONING_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.POIS.P5.FE'    THEN VALUE END) AS MORTALITY_POISONING_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.POIS.P5.MA'    THEN VALUE END) AS MORTALITY_POISONING_MALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.SUIC.P5'       THEN VALUE END) AS MORTALITY_SUICIDE_TOTAL,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.SUIC.FE.P5'    THEN VALUE END) AS MORTALITY_SUICIDE_FEMALE,
    MAX(CASE WHEN VARIABLE = 'WDI_SH.STA.SUIC.MA.P5'    THEN VALUE END) AS MORTALITY_SUICIDE_MALE
FROM src
GROUP BY DATE_KEY, GEO_KEY;
